### PR TITLE
Update Italian language

### PR DESCRIPTION
**Pull request by bovirus**
@CodeDead 

Please merge. Thanks.

### CODE REVIEW

**Comment by CodeDead** [comment]
Thanks for the translations. How can we credit you for your good work? We can add your name and a link of your choosing to the about screen and credits in the README file in this repository OR we can also let you remain anonymous if you want. Please let me know before I merge this.

**Comment by bovirus** [comment]
@CodeDead 

Please add my nick bovirus.
I didn't have a web page to add to the credits
If you think could eb sueful to report problem about Italian language you can add my email bovirus at gmail . com

**Comment by CodeDead** [comment]
Thanks @bovirus ! We've included your changes and made them available in the app. You have been given credits in the README and also in the application's information screen!

Thanks for making the application more accessible for Italian users!

**Comment by bovirus** [comment]
@CodeDead 

I will add to the readme the info about other languages available

Dutch
French
Spanish

**Comment by CodeDead** [comment]
@bovirus no need, this information will be discarded since it is redundant to credit CodeDead

**Comment by bovirus** [comment]
@CodeDead 

No klist of languages for credit.
List of languages available as application specfication.
If  a dutch/spanish/french user read readme didn't find info that language for this conuntries are available.

**Pull request merged**
